### PR TITLE
Polish MicroProfile custom config source backed by Azure KeyVault Secrets using latest apis

### PR DESCRIPTION
**Pull request by majguo**
## Summary 

The PR includes:
* Rewrite using latest APIs
  * MicroProfile 6.0 / Config 3.0.2
  * Azure Java SDK 1.2.14 / azure-security-keyvault-secrets 4.6.3
* Support two options for managing the lifecycle of retrieved keyvault secrets in local: Cached or non-cache
* Use [DefaultAzureCredential](https://learn.microsoft.com/en-us/azure/developer/java/sdk/identity-azure-hosted-auth#default-azure-credential) for authentication, which implements the requirement in #1
* Unit tests
* Restructure the project with a BOM for dependencies management
* Enable dependabot version updates

## Next

The followings are not included in the PR but will be included in the next one:
* Sample apps (Open Liberty and Quarkus) for integration test 
* Add/update readme
* Add javadoc
* Pipeline for build and release

Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

### CODE REVIEW

**Review by edburns — CHANGES_REQUESTED** [review]
- Branch name. You don't have to comply with this suggestion, but I
  find it helpful to use the following convention for topic
  branches. `<githubuserid>-msft-<issue-id>-<shortstring>` In this
  case, it would be
  `majguo-msft-dd-1850094-reactivate-azure-microprofile`. Yes, this is
  long, but long names are not a problem if you have a good text
  editor. One benefit of this approach is that when you make a PR,
  there is an easily searchable unique id.
  
- `pom.xml`

   - In your PR, this top level POM serves as a maven parent POM, in
     addition to having child maven modules. I observe that in
     https://github.com/Azure/azure-javaee-iaas the top level POM is
     **not** the maven parent POM. In that repo, the maven parent POM
     is in `arm-parent`, a child module of the top level POM. There
     are benefits to separating the maven parent POM from being the
     top level POM. Also, looking at
     https://github.com/Azure/azure-sdk-for-java, we see the top level
     POM is called `azure-sdk-all` and it is also not a parent
     POM. Looking further, here are the complete set of parent POMs
     used in that repo.
     
      - azure-client-sdk-parent
      - azure-code-customization-parent
      - azure-cosmos-spark_3_2-12
      - azure-data-sdk-parent
      - azure-perf-test-parent
      - azure-sdk-parent
      - spring-boot-starter-parent
      
      Many of these reside in `sdk/parents`.
      
   - Please rework this PR to make it so the artifact serving as the
     parent POM is in its own maven module. For parity with
     azure-sdk-for-java may as well put it in a
     `parents/microprofile-parent` directory. Then, in the top level
     POM, list that module as first in the modules list, to ensure it
     is built and installed in the local repository before it is used
     in a `<parent>` declaration.

**Comment by edburns** [comment]
Another benefit of my suggested topic branch naming approach is the use of these two aliases.

```bash
alias gitstat="git status > changebundle.txt"
alias gitpush="git add --all; git commit -s -n -F changebundle.txt; git push"
```

If your topic branch is named appropriately, then the first line of your commit log message will always be the branch name, which describes the topic, and your commit/push workflow is.

Ensure your global `gitingore` excludes `changebundle.txt`. Ensure your repo `.gitignore` is sufficiently powerful.

1. `gitstat`
2. edit changebundle.txt
3. `gitpush`

**Comment by majguo** [comment]
> Please rework this PR to make it so the artifact serving as the parent POM is in its own maven module

@edburns Fixed in 4731b06.

**Comment by majguo** [comment]
@backwind1233 FYI - similar to https://github.com/quarkiverse/quarkus-azure-services/pull/142#discussion_r1275949397, I also verified that the application id `az-mp-kv-secrets` is displayed as part of User Agent in log when enabling Azure Java SDK logging:

```
{"az.sdk.message":"HTTP request","method":"GET","url":"https://mpkv071923.vault.azure.net/secrets?maxresults=REDACTED&api-version=7.4","tryCount":"1","Authorization":"REDACTED","Content-Length":"0","Content-Type":"application/json","accept-language":"REDACTED","User-Agent":"az-mp-kv-secrets azsdk-java-azure-security-keyvault-secrets/4.6.3 (17.0.7; Linux; 5.10.102.1-microsoft-standard-WSL2)","contentLength":0}
```

**Comment by backwind1233** [comment]
> 

Do you think we need a Separator here? 
like `az-mp-kv-secrets;azsdk-...`
image

**Comment by backwind1233** [comment]
> nsure your repo `.gitignore` is sufficiently powerful.

Hello @edburns , could you explain more about `Ensure your repo .gitignore is sufficiently powerful.`?
What do you mean by this, sufficiently powerful?
Isn't it enough to just add the `changebundle.txt` to the ignore file?

**Comment by majguo** [comment]
> @majguo Do you think we need a Separator here? like `az-mp-kv-secrets;azsdk-...`

@backwind1233 We only set application id here and it's Azure Java SDK's responsibility to produce the final string for User Agent. Let's just keep it as for now, and do enhancement if required in the future when we work on BI.

**Comment by backwind1233** [comment]
> Another benefit of my suggested topic branch naming approach is the use of these two aliases.
> 
> ```shell
> alias gitstat="git status > changebundle.txt"
> alias gitpush="git add --all; git commit -s -n -F changebundle.txt; git push"
> ```
> 
> If your topic branch is named appropriately, then the first line of your commit log message will always be the branch name, which describes the topic, and your commit/push workflow is.
> 
> Ensure your global `gitingore` excludes `changebundle.txt`. Ensure your repo `.gitignore` is sufficiently powerful.
> 
> 1. `gitstat`
> 2. edit changebundle.txt
> 3. `gitpush`

I created a new alias:

> alias gitsnap="git add --all;git status > changebundle.txt;vim changebundle.txt;git commit -s -n -F changebundle.txt;"

and updated the gitstat="git status > changebundle.txt;vim changebundle.txt"

**Review by edburns — APPROVED** [review]
Thanks. I hope you found the review useful.

**Comment by edburns** [comment]
@backwind1233 wrote:

> Hello @edburns , could you explain more about Ensure your repo .gitignore is sufficiently powerful.? What do you mean by this, sufficiently powerful?

I mean that if your personal process is as I described, the `gitpush` alias includes `git add --all`.  Therefore, you need a `.gitignore` that is powerful enough so that no files are accidentally swept up by the `git add --all`. For example, let's say you decided to convert the codebase to use NodeJS in some way. This will cause a `node_modules` directory to appear. Generally, one never wants to commit such folders to Git. Therefore, if you're adding NodeJS to a thing, you need to make sure the `node_modules` never gets added.

For completeness, the section [on global ignores](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) in the github docs is worth a re-read.

**Pull request merged**
